#pragma once
#include "builtin.h"

// errno
#if NOLIBC
typedef enum : iptr {
  EPERM = iptr(-1),
  ENOENT = iptr(-2),
  ESRCH = iptr(-3),
  EINTR = iptr(-4),
  EIO = iptr(-5),
  ENXIO = iptr(-6),
  E2BIG = iptr(-7),
  ENOEXEC = iptr(-8),
  EBADF = iptr(-9),
  ECHILD = iptr(-10),
  EAGAIN = iptr(-11),
  /* NOTE: on linux these have the same value */
  EWOULDBLOCK = EAGAIN,
  ENOMEM = iptr(-12),
  EACCES = iptr(-13),
  EFAULT = iptr(-14),
  ENOTBLK = iptr(-15),
  EBUSY = iptr(-16),
  EEXIST = iptr(-17),
  EXDEV = iptr(-18),
  ENODEV = iptr(-19),
  ENOTDIR = iptr(-20),
  EISDIR = iptr(-21),
  EINVAL = iptr(-22),
  ENFILE = iptr(-23),
  EMFILE = iptr(-24),
  ENOTTY = iptr(-25),
  ETXTBSY = iptr(-26),
  EFBIG = iptr(-27),
  ENOSPC = iptr(-28),
  ESPIPE = iptr(-29),
  EROFS = iptr(-30),
  EMLINK = iptr(-31),
  EPIPE = iptr(-32),
  EDOM = iptr(-33),
  ERANGE = iptr(-34),
  EDEADLOCK = iptr(-35),
  ENAMETOOLONG = iptr(-36),
  ENOLCK = iptr(-37),
  ENOSYS = iptr(-38),
  ENOTEMPTY = iptr(-39),
  ELOOP = iptr(-40),
  EUNKNOWN_41 = iptr(-41),
  ENOMSG = iptr(-42),
  EIDRM = iptr(-43),
  ECHRNG = iptr(-44),
  EL2NSYNC = iptr(-45),
  EL3HLT = iptr(-46),
  EL3RST = iptr(-47),
  ELNRNG = iptr(-48),
  EUNATCH = iptr(-49),
  ENOCSI = iptr(-50),
  EL2HLT = iptr(-51),
  EBADE = iptr(-52),
  EBADR = iptr(-53),
  EXFULL = iptr(-54),
  ENOANO = iptr(-55),
  EBADRQC = iptr(-56),
  EBADSLT = iptr(-57),
  EUNKNOWN_58 = iptr(-58),
  EBFONT = iptr(-59),
  ENOSTR = iptr(-60),
  ENODATA = iptr(-61),
  ETIME = iptr(-62),
  ENOSR = iptr(-63),
  ENONET = iptr(-64),
  ENOPKG = iptr(-65),
  EREMOTE = iptr(-66),
  ENOLINK = iptr(-67),
  EADV = iptr(-68),
  ESRMNT = iptr(-69),
  ECOMM = iptr(-70),
  EPROTO = iptr(-71),
  EMULTIHOP = iptr(-72),
  EDOTDOT = iptr(-73),
  EBADMSG = iptr(-74),
  EOVERFLOW = iptr(-75),
  ENOTUNIQ = iptr(-76),
  EBADFD = iptr(-77),
  EREMCHG = iptr(-78),
  ELIBACC = iptr(-79),
  ELIBBAD = iptr(-80),
  ELIBSCN = iptr(-81),
  ELIBMAX = iptr(-82),
  ELIBEXEC = iptr(-83),
  EILSEQ = iptr(-84),
  ERESTART = iptr(-85),
  ESTRPIPE = iptr(-86),
  EUSERS = iptr(-87),
  ENOTSOCK = iptr(-88),
  EDESTADDRREQ = iptr(-89),
  EMSGSIZE = iptr(-90),
  EPROTOTYPE = iptr(-91),
  ENOPROTOOPT = iptr(-92),
  EPROTONOSUPPORT = iptr(-93),
  ESOCKTNOSUPPORT = iptr(-94),
  EOPNOTSUPP = iptr(-95),
  EPFNOSUPPORT = iptr(-96),
  EAFNOSUPPORT = iptr(-97),
  EADDRINUSE = iptr(-98),
  EADDRNOTAVAIL = iptr(-99),
  ENETDOWN = iptr(-100),
  ENETUNREACH = iptr(-101),
  ENETRESET = iptr(-102),
  ECONNABORTED = iptr(-103),
  ECONNRESET = iptr(-104),
  ENOBUFS = iptr(-105),
  EISCONN = iptr(-106),
  ENOTCONN = iptr(-107),
  ESHUTDOWN = iptr(-108),
  ETOOMANYREFS = iptr(-109),
  ETIMEDOUT = iptr(-110),
  ECONNREFUSED = iptr(-111),
  EHOSTDOWN = iptr(-112),
  EHOSTUNREACH = iptr(-113),
  EALREADY = iptr(-114),
  EINPROGRESS = iptr(-115),
  ESTALE = iptr(-116),
  EUCLEAN = iptr(-117),
  ENOTNAM = iptr(-118),
  ENAVAIL = iptr(-119),
  EISNAM = iptr(-120),
  EREMOTEIO = iptr(-121),
  EDQUOT = iptr(-122),
  ENOMEDIUM = iptr(-123),
  EMEDIUMTYPE = iptr(-124),
  ECANCELED = iptr(-125),
  ENOKEY = iptr(-126),
  EKEYEXPIRED = iptr(-127),
  EKEYREVOKED = iptr(-128),
  EKEYREJECTED = iptr(-129),
  EOWNERDEAD = iptr(-130),
  ENOTRECOVERABLE = iptr(-131),
  ERFKILL = iptr(-132),
  EHWPOISON = iptr(-133),
} Errno;
#else
/* IWYU pragma: begin_exports */
  #include <errno.h>
/* IWYU pragma: end_exports */
#endif

// syscalls
/* NOTE: sign extension is based solely on the type of `a1, ...` */
#define syscall1(id, a1)                     syscall1_impl(id, uptr(a1))
#define syscall2(id, a1, a2)                 syscall2_impl(id, uptr(a1), uptr(a2))
#define syscall3(id, a1, a2, a3)             syscall3_impl(id, uptr(a1), uptr(a2), uptr(a3))
#define syscall4(id, a1, a2, a3, a4)         syscall4_impl(id, uptr(a1), uptr(a2), uptr(a3), uptr(a4))
#define syscall5(id, a1, a2, a3, a4, a5)     syscall5_impl(id, uptr(a1), uptr(a2), uptr(a3), uptr(a4), uptr(a5))
#define syscall6(id, a1, a2, a3, a4, a5, a6) syscall6_impl(id, uptr(a1), uptr(a2), uptr(a3), uptr(a4), uptr(a5), uptr(a6))

#if ARCH_X64
static iptr syscall1_impl(uptr id, uptr a1) {
  /* NOTE: clang asm is retarded, if you did `: "rdi"(1)`, it wouldn't work... */
  register uptr rax asm("rax") = id;
  register uptr rdi asm("rdi") = a1;
  iptr result;
  asm volatile("syscall"
               : "=rax"(result)
               : "r"(rax), "r"(rdi)
               : "rcx", "r11", "memory");
  return result;
}
static iptr syscall2_impl(uptr id, uptr a1, uptr a2) {
  register uptr rax asm("rax") = id;
  register uptr rdi asm("rdi") = a1;
  register uptr rsi asm("rsi") = a2;
  iptr result;
  asm volatile("syscall"
               : "=rax"(result)
               : "r"(rax), "r"(rdi), "r"(rsi)
               : "rcx", "r11", "memory");
  return result;
}
static iptr syscall3_impl(uptr id, uptr a1, uptr a2, uptr a3) {
  register uptr rax asm("rax") = id;
  register uptr rdi asm("rdi") = a1;
  register uptr rsi asm("rsi") = a2;
  register uptr rdx asm("rdx") = a3;
  iptr result;
  asm volatile("syscall"
               : "=rax"(result)
               : "r"(rax), "r"(rdi), "r"(rsi), "r"(rdx)
               : "rcx", "r11", "memory");
  return result;
}
static iptr syscall4_impl(uptr id, uptr a1, uptr a2, uptr a3, uptr a4) {
  register uptr rax asm("rax") = id;
  register uptr rdi asm("rdi") = a1;
  register uptr rsi asm("rsi") = a2;
  register uptr rdx asm("rdx") = a3;
  register uptr r10 asm("r10") = a4;
  iptr result;
  asm volatile("syscall"
               : "=rax"(result)
               : "r"(rax), "r"(rdi), "r"(rsi), "r"(rdx), "r"(r10)
               : "rcx", "r11", "memory");
  return result;
}
static iptr syscall5_impl(uptr id, uptr a1, uptr a2, uptr a3, uptr a4, uptr a5) {
  register uptr rax asm("rax") = id;
  register uptr rdi asm("rdi") = a1;
  register uptr rsi asm("rsi") = a2;
  register uptr rdx asm("rdx") = a3;
  register uptr r10 asm("r10") = a4;
  register uptr r8 asm("r8") = a5;
  iptr result;
  asm volatile("syscall"
               : "=rax"(result)
               : "r"(rax), "r"(rdi), "r"(rsi), "r"(rdx), "r"(r10), "r"(r8)
               : "rcx", "r11", "memory");
  return result;
}
static iptr syscall6_impl(uptr id, uptr a1, uptr a2, uptr a3, uptr a4, uptr a5, uptr a6) {
  register uptr rax asm("rax") = id;
  register uptr rdi asm("rdi") = a1;
  register uptr rsi asm("rsi") = a2;
  register uptr rdx asm("rdx") = a3;
  register uptr r10 asm("r10") = a4;
  register uptr r8 asm("r8") = a5;
  register uptr r9 asm("r9") = a6;
  iptr result;
  asm volatile("syscall"
               : "=rax"(result)
               : "r"(rax), "r"(rdi), "r"(rsi), "r"(rdx), "r"(r10), "r"(r8), "r"(r9)
               : "rcx", "r11", "memory");
  return result;
}

typedef enum : uptr {
  SYS_read = uptr(0),
  SYS_write = uptr(1),
  SYS_open = uptr(2),
  SYS_close = uptr(3),
  SYS_stat = uptr(4),
  SYS_fstat = uptr(5),
  SYS_lstat = uptr(6),
  SYS_poll = uptr(7),
  SYS_lseek = uptr(8),
  SYS_mmap = uptr(9),
  SYS_mprotect = uptr(10),
  SYS_munmap = uptr(11),
  SYS_brk = uptr(12),
  SYS_rt_sigaction = uptr(13),
  SYS_rt_sigprocmask = uptr(14),
  SYS_rt_sigreturn = uptr(15),
  SYS_ioctl = uptr(16),
  SYS_pread64 = uptr(17),
  SYS_pwrite64 = uptr(18),
  SYS_readv = uptr(19),
  SYS_writev = uptr(20),
  SYS_access = uptr(21),
  SYS_pipe = uptr(22),
  SYS_select = uptr(23),
  SYS_sched_yield = uptr(24),
  SYS_mremap = uptr(25),
  SYS_msync = uptr(26),
  SYS_mincore = uptr(27),
  SYS_madvise = uptr(28),
  SYS_shmget = uptr(29),
  SYS_shmat = uptr(30),
  SYS_shmctl = uptr(31),
  SYS_dup = uptr(32),
  SYS_dup2 = uptr(33),
  SYS_pause = uptr(34),
  SYS_nanosleep = uptr(35),
  SYS_getitimer = uptr(36),
  SYS_alarm = uptr(37),
  SYS_setitimer = uptr(38),
  SYS_getpid = uptr(39),
  SYS_sendfile = uptr(40),
  SYS_socket = uptr(41),
  SYS_connect = uptr(42),
  SYS_accept = uptr(43),
  SYS_sendto = uptr(44),
  SYS_recvfrom = uptr(45),
  SYS_sendmsg = uptr(46),
  SYS_recvmsg = uptr(47),
  SYS_shutdown = uptr(48),
  SYS_bind = uptr(49),
  SYS_listen = uptr(50),
  SYS_getsockname = uptr(51),
  SYS_getpeername = uptr(52),
  SYS_socketpair = uptr(53),
  SYS_setsockopt = uptr(54),
  SYS_getsockopt = uptr(55),
  SYS_clone = uptr(56),
  SYS_fork = uptr(57),
  SYS_vfork = uptr(58),
  SYS_execve = uptr(59),
  SYS_exit = uptr(60),
  SYS_wait4 = uptr(61),
  SYS_kill = uptr(62),
  SYS_uname = uptr(63),
  SYS_semget = uptr(64),
  SYS_semop = uptr(65),
  SYS_semctl = uptr(66),
  SYS_shmdt = uptr(67),
  SYS_msgget = uptr(68),
  SYS_msgsnd = uptr(69),
  SYS_msgrcv = uptr(70),
  SYS_msgctl = uptr(71),
  SYS_fcntl = uptr(72),
  SYS_flock = uptr(73),
  SYS_fsync = uptr(74),
  SYS_fdatasync = uptr(75),
  SYS_truncate = uptr(76),
  SYS_ftruncate = uptr(77),
  SYS_getdents = uptr(78),
  SYS_getcwd = uptr(79),
  SYS_chdir = uptr(80),
  SYS_fchdir = uptr(81),
  SYS_rename = uptr(82),
  SYS_mkdir = uptr(83),
  SYS_rmdir = uptr(84),
  SYS_creat = uptr(85),
  SYS_link = uptr(86),
  SYS_unlink = uptr(87),
  SYS_symlink = uptr(88),
  SYS_readlink = uptr(89),
  SYS_chmod = uptr(90),
  SYS_fchmod = uptr(91),
  SYS_chown = uptr(92),
  SYS_fchown = uptr(93),
  SYS_lchown = uptr(94),
  SYS_umask = uptr(95),
  SYS_gettimeofday = uptr(96),
  SYS_getrlimit = uptr(97),
  SYS_getrusage = uptr(98),
  SYS_sysinfo = uptr(99),
  SYS_times = uptr(100),
  SYS_ptrace = uptr(101),
  SYS_getuid = uptr(102),
  SYS_syslog = uptr(103),
  SYS_getgid = uptr(104),
  SYS_setuid = uptr(105),
  SYS_setgid = uptr(106),
  SYS_geteuid = uptr(107),
  SYS_getegid = uptr(108),
  SYS_setpgid = uptr(109),
  SYS_getppid = uptr(110),
  SYS_getpgrp = uptr(111),
  SYS_setsid = uptr(112),
  SYS_setreuid = uptr(113),
  SYS_setregid = uptr(114),
  SYS_getgroups = uptr(115),
  SYS_setgroups = uptr(116),
  SYS_setresuid = uptr(117),
  SYS_getresuid = uptr(118),
  SYS_setresgid = uptr(119),
  SYS_getresgid = uptr(120),
  SYS_getpgid = uptr(121),
  SYS_setfsuid = uptr(122),
  SYS_setfsgid = uptr(123),
  SYS_getsid = uptr(124),
  SYS_capget = uptr(125),
  SYS_capset = uptr(126),
  SYS_rt_sigpending = uptr(127),
  SYS_rt_sigtimedwait = uptr(128),
  SYS_rt_sigqueueinfo = uptr(129),
  SYS_rt_sigsuspend = uptr(130),
  SYS_sigaltstack = uptr(131),
  SYS_utime = uptr(132),
  SYS_mknod = uptr(133),
  SYS_uselib = uptr(134),
  SYS_personality = uptr(135),
  SYS_ustat = uptr(136),
  SYS_statfs = uptr(137),
  SYS_fstatfs = uptr(138),
  SYS_sysfs = uptr(139),
  SYS_getpriority = uptr(140),
  SYS_setpriority = uptr(141),
  SYS_sched_setparam = uptr(142),
  SYS_sched_getparam = uptr(143),
  SYS_sched_setscheduler = uptr(144),
  SYS_sched_getscheduler = uptr(145),
  SYS_sched_get_priority_max = uptr(146),
  SYS_sched_get_priority_min = uptr(147),
  SYS_sched_rr_get_interval = uptr(148),
  SYS_mlock = uptr(149),
  SYS_munlock = uptr(150),
  SYS_mlockall = uptr(151),
  SYS_munlockall = uptr(152),
  SYS_vhangup = uptr(153),
  SYS_modify_ldt = uptr(154),
  SYS_pivot_root = uptr(155),
  SYS__sysctl = uptr(156),
  SYS_prctl = uptr(157),
  SYS_arch_prctl = uptr(158),
  SYS_adjtimex = uptr(159),
  SYS_setrlimit = uptr(160),
  SYS_chroot = uptr(161),
  SYS_sync = uptr(162),
  SYS_acct = uptr(163),
  SYS_settimeofday = uptr(164),
  SYS_mount = uptr(165),
  SYS_umount2 = uptr(166),
  SYS_swapon = uptr(167),
  SYS_swapoff = uptr(168),
  SYS_reboot = uptr(169),
  SYS_sethostname = uptr(170),
  SYS_setdomainname = uptr(171),
  SYS_iopl = uptr(172),
  SYS_ioperm = uptr(173),
  SYS_create_module = uptr(174),
  SYS_init_module = uptr(175),
  SYS_delete_module = uptr(176),
  SYS_get_kernel_syms = uptr(177),
  SYS_query_module = uptr(178),
  SYS_quotactl = uptr(179),
  SYS_nfsservctl = uptr(180),
  SYS_getpmsg = uptr(181),
  SYS_putpmsg = uptr(182),
  SYS_afs_syscall = uptr(183),
  SYS_tuxcall = uptr(184),
  SYS_security = uptr(185),
  SYS_gettid = uptr(186),
  SYS_readahead = uptr(187),
  SYS_setxattr = uptr(188),
  SYS_lsetxattr = uptr(189),
  SYS_fsetxattr = uptr(190),
  SYS_getxattr = uptr(191),
  SYS_lgetxattr = uptr(192),
  SYS_fgetxattr = uptr(193),
  SYS_listxattr = uptr(194),
  SYS_llistxattr = uptr(195),
  SYS_flistxattr = uptr(196),
  SYS_removexattr = uptr(197),
  SYS_lremovexattr = uptr(198),
  SYS_fremovexattr = uptr(199),
  SYS_tkill = uptr(200),
  SYS_time = uptr(201),
  SYS_futex = uptr(202),
  SYS_sched_setaffinity = uptr(203),
  SYS_sched_getaffinity = uptr(204),
  SYS_set_thread_area = uptr(205),
  SYS_io_setup = uptr(206),
  SYS_io_destroy = uptr(207),
  SYS_io_getevents = uptr(208),
  SYS_io_submit = uptr(209),
  SYS_io_cancel = uptr(210),
  SYS_get_thread_area = uptr(211),
  SYS_lookup_dcookie = uptr(212),
  SYS_epoll_create = uptr(213),
  SYS_epoll_ctl_old = uptr(214),
  SYS_epoll_wait_old = uptr(215),
  SYS_remap_file_pages = uptr(216),
  SYS_getdents64 = uptr(217),
  SYS_set_tid_address = uptr(218),
  SYS_restart_syscall = uptr(219),
  SYS_semtimedop = uptr(220),
  SYS_fadvise64 = uptr(221),
  SYS_timer_create = uptr(222),
  SYS_timer_settime = uptr(223),
  SYS_timer_gettime = uptr(224),
  SYS_timer_getoverrun = uptr(225),
  SYS_timer_delete = uptr(226),
  SYS_clock_settime = uptr(227),
  SYS_clock_gettime = uptr(228),
  SYS_clock_getres = uptr(229),
  SYS_clock_nanosleep = uptr(230),
  SYS_exit_group = uptr(231),
  SYS_epoll_wait = uptr(232),
  SYS_epoll_ctl = uptr(233),
  SYS_tgkill = uptr(234),
  SYS_utimes = uptr(235),
  SYS_vserver = uptr(236),
  SYS_mbind = uptr(237),
  SYS_set_mempolicy = uptr(238),
  SYS_get_mempolicy = uptr(239),
  SYS_mq_open = uptr(240),
  SYS_mq_unlink = uptr(241),
  SYS_mq_timedsend = uptr(242),
  SYS_mq_timedreceive = uptr(243),
  SYS_mq_notify = uptr(244),
  SYS_mq_getsetattr = uptr(245),
  SYS_kexec_load = uptr(246),
  SYS_waitid = uptr(247),
  SYS_add_key = uptr(248),
  SYS_request_key = uptr(249),
  SYS_keyctl = uptr(250),
  SYS_ioprio_set = uptr(251),
  SYS_ioprio_get = uptr(252),
  SYS_inotify_init = uptr(253),
  SYS_inotify_add_watch = uptr(254),
  SYS_inotify_rm_watch = uptr(255),
  SYS_migrate_pages = uptr(256),
  SYS_openat = uptr(257),
  SYS_mkdirat = uptr(258),
  SYS_mknodat = uptr(259),
  SYS_fchownat = uptr(260),
  SYS_futimesat = uptr(261),
  SYS_newfstatat = uptr(262),
  SYS_unlinkat = uptr(263),
  SYS_renameat = uptr(264),
  SYS_linkat = uptr(265),
  SYS_symlinkat = uptr(266),
  SYS_readlinkat = uptr(267),
  SYS_fchmodat = uptr(268),
  SYS_faccessat = uptr(269),
  SYS_pselect6 = uptr(270),
  SYS_ppoll = uptr(271),
  SYS_unshare = uptr(272),
  SYS_set_robust_list = uptr(273),
  SYS_get_robust_list = uptr(274),
  SYS_splice = uptr(275),
  SYS_tee = uptr(276),
  SYS_sync_file_range = uptr(277),
  SYS_vmsplice = uptr(278),
  SYS_move_pages = uptr(279),
  SYS_utimensat = uptr(280),
  SYS_epoll_pwait = uptr(281),
  SYS_signalfd = uptr(282),
  SYS_timerfd_create = uptr(283),
  SYS_eventfd = uptr(284),
  SYS_fallocate = uptr(285),
  SYS_timerfd_settime = uptr(286),
  SYS_timerfd_gettime = uptr(287),
  SYS_accept4 = uptr(288),
  SYS_signalfd4 = uptr(289),
  SYS_eventfd2 = uptr(290),
  SYS_epoll_create1 = uptr(291),
  SYS_dup3 = uptr(292),
  SYS_pipe2 = uptr(293),
  SYS_inotify_init1 = uptr(294),
  SYS_preadv = uptr(295),
  SYS_pwritev = uptr(296),
  SYS_rt_tgsigqueueinfo = uptr(297),
  SYS_perf_event_open = uptr(298),
  SYS_recvmmsg = uptr(299),
  SYS_fanotify_init = uptr(300),
  SYS_fanotify_mark = uptr(301),
  SYS_prlimit64 = uptr(302),
  SYS_name_to_handle_at = uptr(303),
  SYS_open_by_handle_at = uptr(304),
  SYS_clock_adjtime = uptr(305),
  SYS_syncfs = uptr(306),
  SYS_sendmmsg = uptr(307),
  SYS_setns = uptr(308),
  SYS_getcpu = uptr(309),
  SYS_process_vm_readv = uptr(310),
  SYS_process_vm_writev = uptr(311),
  SYS_kcmp = uptr(312),
  SYS_finit_module = uptr(313),
  SYS_sched_setattr = uptr(314),
  SYS_sched_getattr = uptr(315),
  SYS_renameat2 = uptr(316),
  SYS_seccomp = uptr(317),
  SYS_getrandom = uptr(318),
  SYS_memfd_create = uptr(319),
  SYS_kexec_file_load = uptr(320),
  SYS_bpf = uptr(321),
  SYS_execveat = uptr(322),
  SYS_userfaultfd = uptr(323),
  SYS_membarrier = uptr(324),
  SYS_mlock2 = uptr(325),
  SYS_copy_file_range = uptr(326),
  SYS_preadv2 = uptr(327),
  SYS_pwritev2 = uptr(328),
  SYS_pkey_mprotect = uptr(329),
  SYS_pkey_alloc = uptr(330),
  SYS_pkey_free = uptr(331),
  SYS_statx = uptr(332),
  SYS_io_pgetevents = uptr(333),
  SYS_rseq = uptr(334),
  SYS_pidfd_send_signal = uptr(424),
  SYS_io_uring_setup = uptr(425),
  SYS_io_uring_enter = uptr(426),
  SYS_io_uring_register = uptr(427),
  SYS_open_tree = uptr(428),
  SYS_move_mount = uptr(429),
  SYS_fsopen = uptr(430),
  SYS_fsconfig = uptr(431),
  SYS_fsmount = uptr(432),
  SYS_fspick = uptr(433),
  SYS_pidfd_open = uptr(434),
  SYS_clone3 = uptr(435),
  SYS_close_range = uptr(436),
  SYS_openat2 = uptr(437),
  SYS_pidfd_getfd = uptr(438),
  SYS_faccessat2 = uptr(439),
  SYS_process_madvise = uptr(440),
  SYS_epoll_pwait2 = uptr(441),
  SYS_mount_setattr = uptr(442),
  SYS_quotactl_fd = uptr(443),
  SYS_landlock_create_ruleset = uptr(444),
  SYS_landlock_add_rule = uptr(445),
  SYS_landlock_restrict_self = uptr(446),
  SYS_memfd_secret = uptr(447),
  SYS_process_mrelease = uptr(448),
  SYS_futex_waitv = uptr(449),
  SYS_set_mempolicy_home_node = uptr(450),
  SYS_cachestat = uptr(451),
  SYS_fchmodat2 = uptr(452),
  SYS_map_shadow_stack = uptr(453),
} Syscall;
#endif

// common
/* NOTE: everything is a file on linux */
DISTINCT(CINT, FileHandle);
DISTINCT(FileHandle, Handle);
#define INVALID_HANDLE (Handle)(-1)
iptr close(FileHandle file) {
  return syscall1(SYS_close, (uptr)file);
}
iptr write(FileHandle file, rcstring buffer, usize buffer_size) {
  return syscall3(SYS_write, (uptr)file, (uptr)buffer, buffer_size);
}
